import 'dart:convert';
import 'dart:io';

import 'package:content_compiler/content_compiler.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

class _FakeTts implements TtsAdapter {
  _FakeTts(this.id);

  @override
  final String id;

  int calls = 0;

  @override
  Future<List<int>?> synthesize(String text) async {
    calls++;
    return utf8.encode('$id:$text');
  }
}

void main() {
  late Directory cacheDir;

  setUp(() {
    cacheDir = Directory.systemTemp.createTempSync('miras_tts_cache');
  });
  tearDown(() => cacheDir.deleteSync(recursive: true));

  group('CachedTts', () {
    test(
      'synthesizes once, replays from cache, and writes ADAPTER marker',
      () async {
        final fake = _FakeTts('fake:voice');
        final tts = CachedTts(fake, cacheDir);

        final first = await tts.get('سیمرغ');
        final second = await tts.get('سیمرغ');

        expect(first, second);
        expect(fake.calls, 1);
        expect(
          File(p.join(cacheDir.path, 'ADAPTER')).readAsStringSync().trim(),
          'fake:voice',
        );
      },
    );
  });

  group('CacheOnlyTts', () {
    test(
      'replays a cache generated by another adapter under the same keys',
      () async {
        await CachedTts(_FakeTts('fake:voice'), cacheDir).get('سیمرغ');

        final replay = CachedTts(CacheOnlyTts(cacheDir), cacheDir);
        expect(replay.adapter.id, 'fake:voice');
        expect(await replay.get('سیمرغ'), utf8.encode('fake:voice:سیمرغ'));
        expect(replay.assetName('سیمرغ'), startsWith('audio/'));
      },
    );

    test('a cache miss is a hard error, not a silent skip', () async {
      await CachedTts(_FakeTts('fake:voice'), cacheDir).get('سیمرغ');

      final replay = CachedTts(CacheOnlyTts(cacheDir), cacheDir);
      expect(replay.get('عنقا'), throwsStateError);
    });

    test('refuses a cache directory without an ADAPTER marker', () {
      expect(() => CacheOnlyTts(cacheDir), throwsStateError);
    });
  });

  group('PiperTts', () {
    test('id binds voice name and model content', () {
      final model = File(p.join(cacheDir.path, 'fa_IR-voice-medium.onnx'))
        ..writeAsBytesSync([1, 2, 3]);

      final id = PiperTts(model: model).id;
      expect(id, startsWith('piper:fa_IR-voice-medium@'));

      model.writeAsBytesSync([4, 5, 6]);
      expect(PiperTts(model: model).id, isNot(id));
    });
  });

  group('listeningWithoutAudio', () {
    Exercise exercise(String id, ExerciseType type, String vocabId) => Exercise(
      id: id,
      lessonId: 'ch.l01',
      position: 1,
      type: type,
      prompt: {'vocabId': vocabId, 'options': const [], 'correctIndex': 0},
      sourceFile: 'test',
    );

    ContentBundle bundle(List<Exercise> exercises) => ContentBundle(
      chapters: [
        ChapterContent(
          id: 'ch',
          position: 1,
          title: 'فصل',
          subtitle: 'س',
          summary: 'خ',
          sourceFile: 'test',
          lessons: [
            Lesson(
              id: 'ch.l01',
              chapterId: 'ch',
              position: 1,
              type: LessonType.vocab,
              title: 'درس',
              exercises: exercises,
              sourceFile: 'test',
            ),
          ],
        ),
      ],
    );

    test('flags listening exercises whose vocab lacks audio', () {
      final result = listeningWithoutAudio(
        bundle([
          exercise('ch.l01.e01', ExerciseType.listening, 'vocab.covered'),
          exercise('ch.l01.e02', ExerciseType.listening, 'vocab.silent'),
          exercise('ch.l01.e03', ExerciseType.multipleChoice, 'vocab.silent'),
        ]),
        {'vocab.covered'},
      );

      expect(result, ['ch.l01.e02 → vocab.silent']);
    });

    test('passes when every listening vocab has audio', () {
      final result = listeningWithoutAudio(
        bundle([exercise('ch.l01.e01', ExerciseType.listening, 'vocab.a')]),
        {'vocab.a'},
      );

      expect(result, isEmpty);
    });
  });
}
